# Generated by Django 3.2 on 2021-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('description', models.TextField(null=True, verbose_name='説明')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('quantity', models.PositiveIntegerField(verbose_name='在庫')),
                ('published_on', models.DateField(verbose_name='発売日')),
            ],
        ),
    ]
